### PR TITLE
bug(ui-contract-editor):cursor caret last character location corrrected

### LINKED ISSUE #179: Text cursor is in wrong location when selecting after last character in a variable
# Bug Report 🐛
When a user selects after the last character in a variable, the text cursor appears to be slightly outside of the variable, instead of where the text will appear when the user types a character.

## Expected Behavior
Text cursor should be where the text will appear, like this:

image
image

## Current Behavior
image

### PR DESCRIPTION
**Pull request by sanketshevkar**
Signed-off-by: User <shevkar.sanket@gmail.com>

# Closes #179 

### Changes

- display property added in styles.css for variable className

### Flags

- Some extra padding added vertically to variable span due to `display: inline-grid`

### Related Issues
- Issue #179 

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by sanketshevkar** [comment]
I'm sorry, I just this issue was assigned to someone else.

**Comment by irmerk** [comment]
I think that's fine, @khanjasir90 doesn't seem to have come back to it.

**Comment by sanketshevkar** [comment]
@irmerk Can you assign reviewers for this pr.

**Comment by irmerk** [comment]
I believe this [_creates_ the issue](https://deploy-preview-244--ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor) described in #179, I don't think the issue actually exists in our [current code](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor)

**Comment by sanketshevkar** [comment]
> I believe this [_creates_ the issue](https://deploy-preview-244--ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor) described in #179, I don't think the issue actually exists in our [current code](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor)

I guess it does. I've made a video explaining it. 
https://www.loom.com/share/a6271734ab2042959d41cfa338181077

**Comment by sanketshevkar** [comment]
@irmerk this seems to be a browser-specific bug. I found this bug in chrome which is running on Ubuntu 18. I opened the [current code](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor) in Mozilla Firefox, I encountered a new bug altogether, I'm not able to set the cursor caret inside the variable.
https://www.loom.com/share/aac817f00a5f4ae2bb28d89e486ba233

**Pull request closed without merging**
