### PR TITLE
test(ui-markdown-editor): add rtl with sample test - 192

### LINKED ISSUE #192: Add a React DOM Testing Framework
# Feature Request 🛍️

Currently, the web-components library does not have any standardized way of unit testing the React components in this repo. The first step to solving this problem should be to install and configure a test framework with a sample test to allow other contributors to add further tests. 

## Possible Solution
I propose `React Testing Library` as it is now the most popular DOM testing library for React and handles hooks well. https://testing-library.com/docs/react-testing-library/intro

### PR DESCRIPTION
**Pull request by Ian-Yy**
Signed-off-by: YYee <ongyernyee@gmail.com>

# Closes #192 

### Changes

- updated npm script test with SKIP_PREFLIGHT_CHECK mode
- created sample test

### CODE REVIEW

**Review by irmerk — CHANGES_REQUESTED** [review]
Great @Ian-Yy! I think we will want to start out with a simple test using the components in the repo rather than a sample test.

**Comment by Ian-Yy** [comment]
Thanks @irmerk. But the test is actually testing the Leaf component instead of a sample test. Should I create another test?

**Comment by irmerk** [comment]
Ah okay right! And what does `SKIP_PREFLIGHT_CHECK=true` do here?

**Comment by Ian-Yy** [comment]
The `SKIP_PREFLIGHT_CHECK=true` is to handle the dependencies incompatibilities with the parent node_modules.

**Review by DianaLease — APPROVED** [review]
LGTM

**Review by irmerk — APPROVED** [review]

**Pull request merged**
