### PR TITLE
auto scroll enabled in contract editor for dnd

### PR DESCRIPTION
**Pull request by sanketshevkar**
Had to just uncomment the following:
 https://github.com/accordproject/web-components/blob/df00e1770b8d1a234f14a9bb0ccdfb1669f1fb38/packages/ui-contract-editor/src/lib/ContractEditor/index.js#L246.
The auto-scroll works but has a very narrow part at the top and the bottom where you'll have to drag the augmented editor to see the auto-scroll.

# Closes #<CORRESPONDING ISSUE NUMBER>

### Changes

- <ONE>
- <TWO>

### Flags

- <ONE>
- <TWO>

### Related Issues
- Issue #<NUMBER>
- Pull Request #<NUMBER>

### Author Checklist
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Review by jeromesimeon — CHANGES_REQUESTED** [review]
Please sign your commit(s) for the Developer Certificate of Originality (DCO) check.

**Review by DianaLease — CHANGES_REQUESTED** [review]
I don't think this change is necessary. The behavior in this PR is the same as the currently deployed version of the Contract Editor [here](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor).

Can you explain more about "the very narrow part at the top and the bottom" where you need to drag to auto scroll? What causes that? Can we make it less "narrow"?

**Comment by sanketshevkar** [comment]
> I don't think this change is necessary. The behavior in this PR is the same as the currently deployed version of the Contract Editor [here](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor).
> 
> Can you explain more about "the very narrow part at the top and the bottom" where you need to drag to auto scroll? What causes that? Can we make it less "narrow"?
>
There is a very narrow part at the top and bottom around 1rem in size, if you drag the the drag.js component in this area then only you can see the auto scroll effect.
I tried increasing the padding and the border of the body (i assumed that this narrow part would be one among them), but it did not work.
I think we can add some kind of marker in that narrow portion which will be seen only during the dragging state to make it more intuitive.

**Comment by irmerk** [comment]
Closing this PR. I'd recommend opening an issue to discuss what you'd like to see improved and we can figure out the design and plan before doing development work.

**Pull request closed without merging**
