### PR TITLE
fix(ui-markdown-editor): allow image deletion - #320

### LINKED ISSUE #320: Can't Delete image in Markdown editor
# Bug Report 🐛
See this Loom video where I had tried to delete the text and image but the image was not able to delete
Loom link : https://www.loom.com/share/558b1ef9151c45e59de3962ec62def4b
Or see this video:

https://user-images.githubusercontent.com/58624108/112434714-e64fbd00-8d69-11eb-9937-01f9828cf010.mp4

## Expected Behavior
By selecting the image and then clicking the delete/backspace image should get deleted

## Current Behavior
By selecting the image and then clicking the delete/backspace image was not deleted

## Steps to Reproduce

1. Go to markdown editor (https://ap-web-components.netlify.app/?path=/story/markdown-editor--demo)
2. Try to add an image or use an existing sample image
3. Select the image and try to delete it with the delete/backspace key

### Desktop
 - OS: Windows 10[e.g. macOS]
 - Browser: Chrome[e.g. Chrome, Safari]
 - Version: 89.0[e.g. 0.22.15]

### PR DESCRIPTION
**Pull request by K-Kumar-01**
Signed-off-by: k-kumar-01 <kushalkumargupta4@gmail.com>

# Closes #320 <CORRESPONDING ISSUE NUMBER>

Image can be deleted now by pressing either the backspace key or the delete key.

### Changes

- <ONE> Check if the key is backspace and node selected is image. If `true` delete the use `Editor.deleteBackward(editor)`
- <TWO> Check if the key is delete and node selected is image. If `true` delete the use `Editor.deleteFordward(editor)`

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by K-Kumar-01** [comment]
@irmerk 
Requesting your review.

**Comment by Aniruddha-Shriwant** [comment]
This looks great @K-Kumar-01!
But I just noticed a small bug,
Steps to reproduce : 
1. Go to https://deploy-preview-330--ap-web-components.netlify.app/?path=/story/markdown-editor--demo
2. Select the default Image 
3. Hit backspace, Now you will notice that the image was deleted successfully
5. Hit `ctrl+z` or `undo` twice, the image is back again 
7. Now select the image and hit backspace again, you will notice that the last letter of the line above the image is also deleted

@K-Kumar-01 can you verify this?
Is this a bug or it's intentional to work like that?

**Comment by K-Kumar-01** [comment]
> This looks great @K-Kumar-01!
> But I just noticed a small bug,
> Steps to reproduce :
> 
> 1. Go to https://deploy-preview-330--ap-web-components.netlify.app/?path=/story/markdown-editor--demo
> 2. Select the default Image
> 3. Hit backspace, Now you will notice that the image was deleted successfully
> 4. Hit `ctrl+z` or `undo` twice, the image is back again
> 5. Now select the image and hit backspace again, you will notice that the last letter of the line above the image is also deleted
> 
> @K-Kumar-01 can you verify this?
> Is this a bug or it's intentional to work like that?

@Aniruddha-Shriwant 
I found this while I was trying to resolve the issue. However, I left it as such because I didn't think that anyone would do the following steps: `delete->undo->delete`.
So I kept it as such. If there is any change required, I would do it.

**Comment by Aniruddha-Shriwant** [comment]
Yeah @K-Kumar-01 that makes sense 😅

**Pull request merged**
