### PR TITLE
fix(ui-markdown-editor): fixes cursor movement around headings - I260

### LINKED ISSUE #260: 🐛 insertHeadingbreak Bug
# Bug Report 🐛

The cursor would jump one line above when we would press enter from the beginning of any heading text

r91hU4x2ti

## Expected Behavior

The cursor should go down with the heading text as it happens everywhere else

## Steps to Reproduce
1. Put the cursor to the beginning of any heading and press enter.

### Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version 88.0.4324.182 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by d-e-v-esh**
Signed-off-by: d-e-v-esh <59534570+d-e-v-esh@users.noreply.github.com>

# Closes #260

- Before: The cursor would jump one line above when we would press enter from the beginning of any heading text

r91hU4x2ti

+ Now: It works as expected now and stays in the same line

CAeWDpfbXi

### Changes

```diff
+ Transforms.move(editor, { distance: 1, unit: 'character' })
```

### Related Issues
- Issue #260 

### Author Checklist
- 

- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [x] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by d-e-v-esh** [comment]
@irmerk Is this ok now?

**Comment by irmerk** [comment]
Looks like it! Still want to change the commit and PR title to our format.

NOTE: This is built off #261

**Comment by d-e-v-esh** [comment]
@irmerk  I'll get to that tomorrow for sure. Really appreciate the help.

**Comment by d-e-v-esh** [comment]
@irmerk Is the title good?

**Comment by Michael-Grover** [comment]
It looks like the cursor still jumps to the line above the heading if you refresh the page and don't click anywhere, then press enter. See the recording for more detail

https://www.loom.com/share/ec48136714d44e218d12f00bc29b7b50

**Comment by d-e-v-esh** [comment]
@Michael-Grover That is true... Do you have any idea what might be causing the problem? Can it be some memoized value that gets updated when we interact with the site?

**Comment by irmerk** [comment]
That could be the case. This might even be a bug deep within [Slate](https://docs.slatejs.org/), it could be useful to check there.

**Comment by d-e-v-esh** [comment]
@Michael-Grover @irmerk  It might be some sort of bug in Slate at someplace, but in this case I think I have found what is causing the main problem and it mostly fixes all the issues.
I want to know what is the intended purpose of having a separate `headingBreak` function that would be different from a `linebreak`. All I can gather up is that it adds 2 lines on the press of enter from any heading (H1, H2, H3) instead of just one. Is that all or am I missing something?

**Comment by irmerk** [comment]
I'd have to look into it further, but I believe that comes from https://github.com/accordproject/web-components/pull/220

**Comment by d-e-v-esh** [comment]
@irmerk Thanks! I think I fully understand it now. Working on fixing this.

**Review by dselman — APPROVED** [review]
LGTM! Thank you.

**Review by irmerk — CHANGES_REQUESTED** [review]
Observations from @Michael-Grover [here](https://github.com/accordproject/web-components/pull/262#issuecomment-785184733) still need to be fixed.

**Pull request closed without merging**
