### PR TITLE
fix(ui-markdown-editor): Resize clickable area - #318

### LINKED ISSUE #318: Clickable area of "insert image" and "page break" is much smaller than other items in the formatting toolbar
# Bug Report 🐛

For some reason, the clickable area of the "insert image" and "page break" icons in the formatting toolbar is much smaller than the clickable area of all of the other icons in the formatting toolbar. This makes the icons harder to click, and is visually inconsistent.

The red squares roughly show the clickable areas:
image

another comparison:

image
image
It's hard to see, but there's a gray rounded square that appears when hovering over the clickable area of an icon. The above images show that the gray square is larger for most icons like "hyperlink", but very small for icons like "page break"

### PR DESCRIPTION
**Pull request by K-Kumar-01**
Signed-off-by: k-kumar-01 <kushalkumargupta4@gmail.com>

# Closes #318 <CORRESPONDING ISSUE NUMBER>

Clickable area increased of page break and image icons.

### Changes

- <ONE> Updated the width and padding of the icons

### Screenshots or Video

**The height of different icons**
Screenshot from 2021-03-25 12-39-23
Screenshot from 2021-03-25 12-39-18
Screenshot from 2021-03-25 12-39-14
Screenshot from 2021-03-25 12-39-10

**Hovering over the icon**
Screenshot from 2021-03-25 12-39-05
Screenshot from 2021-03-25 12-38-46
Screenshot from 2021-03-25 12-38-44

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
Requesting your review

**Comment by Hanaffi** [comment]
@irmerk  @Michael-Grover I have tested it manually and it works fine!

**Review by Michael-Grover — APPROVED** [review]
this looks good to me, thanks 👍

**Comment by Michael-Grover** [comment]
This requires a review from an maintainer who is an engineer to be merged

**Review by irmerk — APPROVED** [review]

**Pull request merged**
