### PR TITLE
The z-index of optionaltooltip was set to 1000 Clause template buttons overlap tooltips #185 solved

### PR DESCRIPTION
**Pull request by Manan17**
# Closes #<CORRESPONDING ISSUE NUMBER>

### Changes

- <ONE>The z-index of optionaltooltip was set to 1000 so that it does not come under the clause buttons

### Author Checklist
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Review by DianaLease — CHANGES_REQUESTED** [review]
In the CSS file, you have the z-index set to `10000` which seems very high. I would set that to `1000` like you have said in the description if that is high enough to be in front of the button icons. Making it too high means it might cause users to have super high z-indexes for other things in their app like pop up modals.

Also, does the optional tooltip where you are setting inline styles in `OptionalBoolean.js` have the class name `optionalTooltip` ? Why would we need to have a z-index in both the inline styling in the javascript file and in the styling in the css file? I would prefer to just have it in the CSS file and then make sure the tooltips have the correct classes on them.

Thanks!

**Comment by irmerk** [comment]
> In the CSS file, you have the z-index set to `10000` which seems very high. I would set that to `1000` like you have said in the description if that is high enough to be in front of the button icons. Making it too high means it might cause users to have super high z-indexes for other things in their app like pop up modals.

Also referenced in https://github.com/accordproject/web-components/pull/190

Same thoughts as that PR: 
> Great, thanks! Do we know what the `z-index` is of the buttons? We should make this just one more than that.
> 
> Also you'll want to fix some issues with the commits and PR by following the [contribution guide](https://github.com/accordproject/techdocs/blob/master/CONTRIBUTING.md#-pull-request-submission-guidelines)

**Comment by Manan17** [comment]
Yes the z-index of the buttons is 1.

**Comment by Manan17** [comment]
> In the CSS file, you have the z-index set to `10000` which seems very high. I would set that to `1000` like you have said in the description if that is high enough to be in front of the button icons. Making it too high means it might cause users to have super high z-indexes for other things in their app like pop up modals.
> 
> Also, does the optional tooltip where you are setting inline styles in `OptionalBoolean.js` have the class name `optionalTooltip` ? Why would we need to have a z-index in both the inline styling in the javascript file and in the styling in the css file? I would prefer to just have it in the CSS file and then make sure the tooltips have the correct classes on them.
> 
> Thanks!

I did apply it in one of the file but it wasn't showing any results. And then I applied in the other one that also didn't show any results. So I had to apply in both of the files.

**Comment by irmerk** [comment]
Please address the changes requested and we can merge this.

**Comment by Manan17** [comment]
> In the CSS file, you have the z-index set to `10000` which seems very high. I would set that to `1000` like you have said in the description if that is high enough to be in front of the button icons. Making it too high means it might cause users to have super high z-indexes for other things in their app like pop up modals.
> 
> Also, does the optional tooltip where you are setting inline styles in `OptionalBoolean.js` have the class name `optionalTooltip` ? Why would we need to have a z-index in both the inline styling in the javascript file and in the styling in the css file? I would prefer to just have it in the CSS file and then make sure the tooltips have the correct classes on them.
> 
> Thanks!

The changes have been applied

**Comment by irmerk** [comment]
Circling back on this - You'll still need to apply the changes.

**Comment by dselman** [comment]
@DianaLease should we close this?

**Pull request closed without merging**
