### PR TITLE
feat(ui-markdown-editor): heading refactor - #293

### LINKED ISSUE #293: Addition of Heading 4, Heading 5, and Heading 6 and updation of existing headings
# Feature Request 🛍️

Updating the Existing Heading Size and addition of Heading 4, Heading 5 and, Heading 6 into the dropdown menu.

## Use Case

`Heading 1` = 25px => Stays the same
`Heading 2` = 25px => Left-aligned to differentiate from H1
`Heading 3` = 20px
`Heading 4` = 18px
`Heading 5` = 16px
`Heading 6` = 14px => Same size as a normal paragraph, All capital letters, The same text formatting as the text used in Page Break:

110824137-c516a900-8260-11eb-9ba8-a5a0457bcc8b

### PR DESCRIPTION
**Pull request by d-e-v-esh**
Signed-off-by: d-e-v-esh <59534570+d-e-v-esh@users.noreply.github.com>

# Closes #293

### Changes

- Added Heading 4, Heading 5, and Heading 6 and change font sizes of existing heading in the following manner:
- `Heading 1` = 25px => Stays the same
- `Heading 2` = 25px => Left-aligned to differentiate from H1
- `Heading 3` = 20px
- `Heading 4` = 18px
- `Heading 5` = 16px
- `Heading 6` = 14px => Same size as a normal paragraph, All capital letters, The same text formatting as the text used in Page Break
- Added new headings in the `isBlockHeading` function that tells if a block is heading or not.

### Flags

- There are few problems existing in the headings especially `Heading 6`. This is basically occurring because a few of the CSS properties are not defined so to make things look better, web browsers add them by default under [user agent stylesheet](https://stackoverflow.com/questions/12582624/what-is-a-user-agent-stylesheet).
- This problem was messing up the styling of Heading 6 but this is good enough for a fix for now. This is not optimal because overriding properties of few elements and not all create a mismatch. An optimal fix would require discussing what would be the best values for the missing properties and then adding them so everything is in our control. See comments in #293
- We can create a separate issue for that and I can work on it then if that sounds good.

### Screenshots or Video

cU8uqozyuj

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [x] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [x] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Review by irmerk — CHANGES_REQUESTED** [review]
I'll need to do some investigating into this.

**Comment by Michael-Grover** [comment]
The styling looks good. Is the font size of H5 16px? It looks a bit smaller, and when I inspect the element, it appears to be 1rem, so I can't confirm whether it's 16px or not.

**Comment by d-e-v-esh** [comment]
@Michael-Grover Ya, it might look smaller compared to H6 because it is not all uppercase. 
1rem is equivalent to 16px so H5 font size is 16px.


chrome_azPc6jxkxK

**Comment by irmerk** [comment]
This all looks good to me, @Michael-Grover can I get your review?

**Review by Michael-Grover — APPROVED** [review]
lgtm

**Review by irmerk — APPROVED** [review]

**Comment by irmerk** [comment]
I agree @d-e-v-esh that you should at least make an Issue around the CSS override, so we don't forget about it.

**Comment by d-e-v-esh** [comment]
@irmerk I created #327. You can assign that to me.

**Pull request merged**
