### PR TITLE
feat(markdown-editor) : SHIFT+ENTER inserts a linebreak

### LINKED ISSUE #153: Support Hardbreaks in Markdown
# Feature Request 🛍️
Hardbreaks are handled in the [commonmark spec](https://spec.commonmark.org/0.17/#hard-line-breaks), and should be supported in the editor

## Use Case
A user would expect the editor to respect their wishes to maintain extra spaces

## Possible Solution
A toolbar button or hotkey shortcut?

## Context
This should persist:
image

Via a `something.md` file which looks like: 
```md
Foo\
\
\
bar
```

### PR DESCRIPTION
**Pull request by dselman**
Signed-off-by: Dan Selman <danscode@selman.org>

# Closes #153 

Also: https://github.com/accordproject/web-components/issues/182
Also: https://github.com/accordproject/web-components/issues/49
Also: https://github.com/accordproject/web-components/issues/41

### Changes
- Adds a keyboard handler for SHIFT+ENTER which inserts a LINEBREAK into the Slate DOM

### Flags
- HTML copy/paste requires a fix in markdown-html

### Screenshots or Video
https://www.loom.com/share/a1458a6fece0468088e2fef776e99d8f

### CODE REVIEW

**Comment by irmerk** [comment]
Screen Shot 2020-09-11 at 8 19 12 AM

**Comment by irmerk** [comment]
One issue is you are unable to exit a block quote with pressing <kbd>ENTER</kbd> twice.

**Review by Michael-Grover — APPROVED** [review]
lgtm

**Comment by DianaLease** [comment]
> One issue is you are unable to exit a block quote with pressing ENTER twice.

I can reproduce this too. In the deployed version, we are able to exit block quotes by hitting enter twice. In this one, we aren't. Exiting lists by hitting enter twice still works.

**Comment by Michael-Grover** [comment]
Pressing shift+enter right before a Clause Template causes an error

https://www.loom.com/share/fea2e40ff37d4ddfb885e90cc00854df

image

**Comment by Michael-Grover** [comment]
actually I'm getting this error more than just when I press shift+enter before a Smart Clause, is anyone else experiencing this?

**Comment by dselman** [comment]
> actually I'm getting this error more than just when I press shift+enter before a Clause Template, is anyone else experiencing this?

Can you create a new issue for this please? It sounds like this is not a regression introduced by this PR.

**Comment by dselman** [comment]
The issue breaking out of block quotes seems to be related to:
https://github.com/accordproject/web-components/blob/master/packages/ui-markdown-editor/src/lib/plugins/withLists.js

(It's pretty confusing that the `withLists` plugin is dealing with block quotes imo). 

@DianaLease @irmerk I don't remember writing this — do either of you understand how this code works? It appears to be sensitive to the presence of the `LINEBREAK` node (which also have empty text), because breaking out of block quotes works until you insert a `LINEBREAK`, then it no longer works.

**Comment by dselman** [comment]
Pushed a fix to this. The issue appears to be that after we insert a linebreak we get text nodes that don't have `"object" : "text"` set, so I've added some defensive checks for this.

**Review by DianaLease — CHANGES_REQUESTED** [review]
This fixes the escaping block quote issue! Looks like we need to also fix the issue Michael mentioned. I can reproduce getting this error in the Contract Editor component when hitting `shift+enter`:
```
Cannot read property 'src' of undefined
```

**Comment by DianaLease** [comment]
> This fixes the escaping block quote issue! Looks like we need to also fix the issue Michael mentioned. I can reproduce getting this error in the Contract Editor component when hitting `shift+enter`:
> 
> ```
> Cannot read property 'src' of undefined
> ```

I think it is specific to this PR as I can only reproduce it in the netlify for this PR. @Michael-Grover, what did you mean by `actually I'm getting this error more than just when I press shift+enter before a Clause Template`? Can you only reproduce it by hitting `shift + enter` in other places or by doing things besides `shift + enter`? And can you reproduce it in the currently deployed version of web-components?

**Comment by Michael-Grover** [comment]
I can reproduce it by pressing shift+enter in other places, not just directly before the Smart Clause. The error appears to only happen in this PR. I tried it in https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor and did not encounter the error.

**Comment by dselman** [comment]
Copy/paste support for line breaks requires merging this PR and releasing `markdown-html`
https://github.com/accordproject/markdown-transform/pull/325

**Review by DianaLease — APPROVED** [review]
LGTM

**Pull request merged**
