### PR TITLE
#278 Solved - Paragraph styling options obscured by Clause Template

### LINKED ISSUE #278: Paragraph styling options obscured by Clause Template
# Bug Report 🐛
Paragraph styling options are obscured by Clause Template
image

## Expected Behavior
the paragraph styling options dropdown should be in front of all content so that users can choose their styling option.

## Possible Solution
Change the Z-index of some elements of the UI

## Steps to Reproduce
1. go to the [contract editor in Netlify](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor)
2. Hover over "normal" on the left side of the formatting toolbar
3. See that the dropdown is covered by the clause template
image

## Context (Environment)
Mac OS, Chrome

### PR DESCRIPTION
**Pull request by naveen8801**
# Closes #278

This issue is solved by changing some style (z -index) .

### Changes

Changes are made in style of ' ClauseWrapper ' in index.js of ' Clause ' under ui-contract-editor .

Before - 

      style = {{
                    userSelect: `${props.readOnly ? 'text' : 'none'}`,
                    padding: '3px',
           }}

After -

     style = {{
                    userSelect: `${props.readOnly ? 'text' : 'none'}`,
                    padding: '3px',
                    zIndex: '-1',
           }}

### Screenshots or Video

After changes - 
Screenshot (23)

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by d-e-v-esh** [comment]
@naveen8801 Were you able to replicate the issue locally? For some reason, this issue was not appearing on my local build and it was working like normal.

**Comment by naveen8801** [comment]
> replicate the issue locally

Hii @d-e-v-esh  , you should check this  https://github.com/accordproject/web-components/blob/79bc7d143ae01cdc01c379116962a26675b89f77/packages/ui-contract-editor/src/components/Clause/index.js#L118.

OS - windows 10

**Comment by irmerk** [comment]
I believe @d-e-v-esh is working on #278?

**Comment by d-e-v-esh** [comment]
@irmerk I haven't started on this issue yet, so you can assign this to him if this PR is good.

**Comment by naveen8801** [comment]
> @irmerk I haven't started on this issue yet, so you can assign this to him if this PR is good.

thanks @d-e-v-esh

**Comment by d-e-v-esh** [comment]
@naveen8801 There was some problem probably but now I'm able to replicate the issue too. So that's great.

**Pull request closed without merging**
