### PR TITLE
fix(ui-contract-editor): Highlight read-only text clause template - i242

### LINKED ISSUE #242: Users can not highlight read only text in a clause template
# Bug Report 🐛
Users currently can not highlight read only text in a clause template. A user should be able to highlight read only text, but not be able to change the text. A user may want to highlight read only text so that they can copy and paste it

## Steps to Reproduce

1.  go to the [contract editor demo in the storybook](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor)
2. go to "knobs" and switch on "read only"
3. Try to highlight text in a clause template. it is not possible but should be.
image

### PR DESCRIPTION
**Pull request by K-Kumar-01**
Signed-off-by: k-kumar-01 <kushalkumargupta4@gmail.com>

# Closes #242 <CORRESPONDING ISSUE NUMBER>

Users are able to highlight read-only text in the clause template.

### Changes

- <ONE> user-select property changed in clause wrapper

### Screenshots or Video

Screenshot from 2021-02-15 15-30-03

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by irmerk** [comment]
I don't think this is the implementation we'd want. If you click anywhere in the clause while `readOnly` is true, the entire clause is selected.

**Comment by K-Kumar-01** [comment]
> I don't think this is the implementation we'd want. If you click anywhere in the clause while `readOnly` is true, the entire clause is selected.

I had doubts whether we had to make it all selectable or some parts of it so I stuck to `user-select:all`
I think `user-select: none` would work as it would make the content selectable which might be desired.
@irmerk 
Would it be fine If some parts are highlightable instead if the entire clause in the `readOnly` state

**Comment by irmerk** [comment]
I think @Michael-Grover should take the lead on this one as far as UX goes.

**Comment by K-Kumar-01** [comment]
@Michael-Grover Any updates on this?

**Comment by dselman** [comment]
> @Michael-Grover Any updates on this?

@Michael-Grover is on vacation this week. The behaviour I think users will want is that they can select any of the text (in whole, or in part) of the document, including clauses - irrespective of whether the editor is in read/write or read-only mode. 

As far as I can tell this seems to be the case, in Safari at least. I tested that copy/paste worked into a Google Doc and got quite good results. Paste back into the editor had some issues, but that should be covered under a separate issue.

**Comment by K-Kumar-01** [comment]
> 
> @Michael-Grover is on vacation this week. The behaviour I think users will want is that they can select any of the text (in whole, or in part) of the document, including clauses - irrespective of whether the editor is in read/write or read-only mode.
> 
@dselman 
Selecting any part of the text or whole can be implemented. I just had a doubt that if one can select any part of the text then they can edit the text in clause(when `readOnly:false`), if that is acceptable then I can implement this feature. There is no issue in `readOnly` knob regarding this.

**Comment by Michael-Grover** [comment]
Hi @K-Kumar-01 , thanks again for taking on this issue. I'm back from my vacation, so I can give some clarification about the expected behavior.

I think we should allow the user to choose what text they want to highlight, instead of forcing them to highlight the entire clause template. See the video for clarification.

https://www.loom.com/share/8c31e6837f8546b784f915bb26ede005

Here are some examples of a user choosing what they want to highlight in read-only text.

image
image

**Comment by K-Kumar-01** [comment]
> Hi @K-Kumar-01 , thanks again for taking on this issue. I'm back from my vacation, so I can give some clarification about the expected behavior.
> 
> I think we should allow the user to choose what text they want to highlight, instead of forcing them to highlight the entire clause template. See the video for clarification.
> 
> https://www.loom.com/share/8c31e6837f8546b784f915bb26ede005
> 
> Here are some examples of a user choosing what they want to highlight in read-only text.
> 
> image
> image

@Michael-Grover 
Thanks for the clarification. I had a small doubt. If `readOnly: false`  then should the text inside the clause template be editable? Rest for `readOnly: true` I think I got what I need to do.

**Comment by K-Kumar-01** [comment]
> > Hi @K-Kumar-01 , thanks again for taking on this issue. I'm back from my vacation, so I can give some clarification about the expected behavior.
> > I think we should allow the user to choose what text they want to highlight, instead of forcing them to highlight the entire clause template. See the video for clarification.
> > https://www.loom.com/share/8c31e6837f8546b784f915bb26ede005
> > Here are some examples of a user choosing what they want to highlight in read-only text.
> > image
> > image
> 
> @Michael-Grover
> Thanks for the clarification. I had a small doubt. If `readOnly: false` then should the text inside the clause template be editable? Rest for `readOnly: true` I think I got what I need to do.

@Michael-Grover 
Any updates here?

**Comment by Michael-Grover** [comment]
@K-Kumar-01 The behavior of readOnly:false shouldn't change. This PR should only address allowing users to highlight text in a read only clause template.

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I have updated my PR to highlight the text while retaining the original functionalities. Let me know if there is any change required.

**Review by Michael-Grover — APPROVED** [review]
@K-Kumar-01 Thanks, the functionality looks good to me. I think we should get an engineer's review before merging, like @jeromesimeon or @irmerk

**Comment by dselman** [comment]
> @K-Kumar-01 Thanks, the functionality looks good to me. I think we should get an engineer's review before merging, like @jeromesimeon or @irmerk

Selection seems strange (Safari) and it seems different if you select forwards, or select backwards.

Forwards:

image

Backwards:

image

**Comment by Michael-Grover** [comment]
@dselman that's not in read only mode, right?

I'm seeing the same behavior in Google Chrome.

It looks like in this PR, the user can no longer highlight a combination of clause template text and normal text in editing mode. Users can do this in the current version of storybook here https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor.
We want to keep this functionality from the current version of the storybook, so that users can highlight a combination of clause template text and normal text.

https://www.loom.com/share/9ff9ecd27fbf409ea244a1918b1a612c

**Comment by K-Kumar-01** [comment]
> > @K-Kumar-01 Thanks, the functionality looks good to me. I think we should get an engineer's review before merging, like @jeromesimeon or @irmerk
> 
> Selection seems strange (Safari) and it seems different if you select forwards, or select backwards.
> 
> Forwards:
> 
> image
> 
> Backwards:
> 
> image

@dselman 
Could you please confirm that the [original demo](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor) in safari is also having the issue or not. 
Also, the continuous selection of paragraphs with clause seems to be affected by my approach as i saw. I will try to find an alternative solution

**Comment by K-Kumar-01** [comment]
@dselman @Michael-Grover 
I have updated my PR.
Also a video showing the working of my PR
https://www.loom.com/share/738f544d7cd442bb9075f3003ccc26b4

**Review by dselman — APPROVED** [review]
Works great for me. Thank you!

**Comment by Michael-Grover** [comment]
Looks great, thanks @K-Kumar-01 !

**Pull request merged**
