### PR TITLE
feat(ui-markdown-editor): Added Code Block Support - I30

### LINKED ISSUE #30: Markdown support: Code blocks
**Is your feature request related to a problem? Please describe.**
Code blocks are a useful markdown feature. It would be nice if the editor supports them.

**Describe the solution you'd like**
The ability to create/edit/delete code blocks.

Maybe the ability to turn into a selection into a code block would be nice as well/

### PR DESCRIPTION
**Pull request by K-Kumar-01**
Signed-off-by: k-kumar-01 <kushalkumargupta4@gmail.com>

# Closes #30 <CORRESPONDING ISSUE NUMBER>

One can now make use of code blocks via a formatting toolbar.

### Changes

- <ONE> Added new button.
- <TWO> Added proper styling to the blocks
- <THREE> Wraps the selected nodes in the code block

### Flags

- <ONE> Not fully featured
- <TWO> Pressing enter many times does not exist the block

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by K-Kumar-01** [comment]
@jeromesimeon @irmerk 
I have opened a corresponding PR for a better understanding. Let me know if there are any changes required.

**Comment by K-Kumar-01** [comment]
@dselman @jeromesimeon @DianaLease @mttrbrts 
Requesting your review

**Review by DianaLease — COMMENTED** [review]
This looks great! I'm not sure about the toolbar icon though, maybe @Michael-Grover has thoughts.

**Comment by K-Kumar-01** [comment]
> This looks great! I'm not sure about the toolbar icon though, maybe @Michael-Grover has thoughts.

I had no idea about the icon so I just used half the `code` icon for demo purposes. :sweat_smile: 
Maybe we can write CB as the logo which depicts the code blocks.

**Comment by DianaLease** [comment]
> I had no idea about the icon so I just used half the `code` icon for demo purposes. 😅
> Maybe we can write CB as the logo which depicts the code blocks.

Maybe something like `<block/>` to distinguish it from the `</>` inline code icon. or 3 backticks (```), but that might be vague to those who are unfamiliar with markdown.

**Comment by K-Kumar-01** [comment]
> > I had no idea about the icon so I just used half the `code` icon for demo purposes. sweat_smile
> > Maybe we can write CB as the logo which depicts the code blocks.
> 
> Maybe something like `<block/>` to distinguish it from the `</>` inline code icon. or 3 backticks (```), but that might be vague to those who are unfamiliar with markdown.

I think that we should also see what @Michael-Grover thinks about these logos or if he has any other design in mind.

**Comment by Michael-Grover** [comment]
it looks like adding this new icon has increased the width of the toolbar, resulting in some CSS issues in the contract editor, for example if you set a paragraph's style to a heading, the style dropdown becomes blank.
image

Also in the markdown editor, if you reduce the screen width, the icons in the toolbar start to shrink.

image

Maybe the 15px margin between icons could be reduced so that the additional icon can fit in the toolbar without causing CSS issues.
image

**Comment by Michael-Grover** [comment]
What's the source of these icons? Are they semantic UI or custom icons like SVGs?

Also @K-Kumar-01 I recommend looking at other editors that use inline code and code blocks and see how they differentiate between the two icons. For example Slack has an inline code and code block icon:

image

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
> Also in the markdown editor, if you reduce the screen width, the icons in the toolbar start to shrink.

I was not able to reproduce this one. In my local machine, it is working as expected

>Maybe the 15px margin between icons could be reduced so that the additional icon can fit in the toolbar without causing CSS issues.

I have reduced the margin to 10px for safer side.

>it looks like adding this new icon has increased the width of the toolbar, resulting in some CSS issues in the contract editor, for example if you set a paragraph's style to a heading, the style dropdown becomes blank.

Now in this, the PR was created before the merging of [this PR](https://github.com/accordproject/web-components/pull/283). Hence the style block was not refreshing and the above occurred.

Also, I have updated my PR. It contains the following updates:
1. New icon for the code block
2. Hotkey implementation.

@DianaLease @irmerk @Michael-Grover 
Requesting your reviews on this.
Let me know if any changes are required. :smiley:

**Comment by Michael-Grover** [comment]
@K-Kumar-01 thanks for the changes. Do you have the SVG for the icon you chose? I'd like to make some edits to it.
Also it looks like the width of the contract editor became narrower as a result of this PR. Let's see if we can keep the contract editor width the same.

**Comment by K-Kumar-01** [comment]
@Michael-Grover 

>Do you have the SVG for the icon you chose? I'd like to make some edits to it.

It's in the file [code_block.js](https://github.com/accordproject/web-components/pull/289/files#diff-2ba25caed8da7ccffa99bab64c210161db192a9b1414b7fe0a52431353b5d64d) in the icons folder

> Also it looks like the width of the contract editor became narrower as a result of this PR. Let's see if we can keep the contract editor width the same.

Should I revert the margin to the original `15px` instead of the changed `10px`?

**Comment by Michael-Grover** [comment]
Do you have an .svg file of the icon that I can open in something like Adobe Illustrator to edit? I'm not sure what to do with the code you shared.

Can we keep the width of the contract editor the same while having the distance between icons be 10px?

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
> Do you have an .svg file of the icon that I can open in something like Adobe Illustrator to edit? I'm not sure what to do with the code you shared.
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="#626262"><path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/><path d="M6.854 4.646a.5.5 0 0 1 0 .708L4.207 8l2.647 2.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 0 1 .708 0zm2.292 0a.5.5 0 0 0 0 .708L11.793 8l-2.647 2.646a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708 0z"/></g></svg>
```
You can either directly paste the above code in adobexD, Figma or choose the following zip:
[code-block.zip](https://github.com/accordproject/web-components/files/6167269/code-block.zip)

The [site](https://iconify.design/icon-sets/?query=code) where I found the logo.

> Can we keep the width of the contract editor the same while having the distance between icons be 10px?

I will experiment and see if I am able to keep the width same

**Comment by Michael-Grover** [comment]
@K-Kumar-01 I adjusted the SVG to be a bit thicker, does this file work?
[code-block.svg.zip](https://github.com/accordproject/web-components/files/6173222/code-block.svg.zip)

**Comment by K-Kumar-01** [comment]
> @K-Kumar-01 I adjusted the SVG to be a bit thicker, does this file work?
> [code-block.svg.zip](https://github.com/accordproject/web-components/files/6173222/code-block.svg.zip)

@Michael-Grover 
Image depicting the new logo.
Screenshot from 2021-03-19 23-39-44

>Can we keep the width of the contract editor the same while having the distance between icons be 10px?

Also, I tried keeping the width the same without margin (used padding). It had the same effect though i would prefer margin as padding required more styling.
So now should i go with `margin` or `padding`?

**Comment by Michael-Grover** [comment]
I don't think the width of the contract editor should be based on the width of the formatting toolbar. Is that currently the case? @DianaLease @irmerk what do you think?

I'd like to make sure the width of the contract editor is consistent and doesn't change by a few pixels whenever we make a change to the formatting toolbar.

@K-Kumar-01 it's hard to tell from the picture but it looks like the new icon is darker than the others. Do you know what controls the color of the icon? Is is something in the code or in the SVG? The icons become darker when they are selected, so I thought something in the code controls the color.

Also let's make sure the icon is centered in its container
image

**Comment by Michael-Grover** [comment]
@K-Kumar-01 I made some minor edits to the svg. 
[code-block.svg 2.zip](https://github.com/accordproject/web-components/files/6173435/code-block.svg.2.zip)

If you send another picture, can you zoom in on the formatting toolbar a bit more please? The detail in the last picture was a bit blurry.

Thanks again for the work on this 👍

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
Some updated pictures of the toolbar:
Images containing the latest svg file 
Screenshot from 2021-03-20 13-05-41
Screenshot from 2021-03-20 13-05-36

This is the picture of `code-block.svg.zip`(the initial file).
Screenshot from 2021-03-20 13-05-04

In my opinion, the new icon looks good enough for a codeblock and better than the previous one.Let me know if you require more images? Also, should I make a PR with this icon?

>I don't think the width of the contract editor should be based on the width of the formatting toolbar.

I experimented with some contract editor styles and here are the images:

**Current styling**
Screenshot from 2021-03-20 13-20-13

**Contract editor with no width specified**
Screenshot from 2021-03-20 13-20-36

**Contract editor with no width specified and a `min-width:min-content`**
**Clasue template with a `min-width:570px` and `max-width:80%`**
Screenshot from 2021-03-20 13-37-47

The last image resembles the current styling of template most aaccurately with benfit that the contract editor width won't depend on width of formatting toolbar.

Let me know which styles can we adopt or if there are any changes required.

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
Any updates on this?

**Comment by Michael-Grover** [comment]
@K-Kumar-01 thanks for the changes. The icon looks a lot better. I'm interested in input on the width issues from someone who is more familiar with the contract editor than me, like @DianaLease or @irmerk. For context, I'd like to make sure the width of the contract editor is consistent and doesn't change by a few pixels whenever we make a change to the formatting toolbar. In Google Docs or Microsoft Word, the default document width is consistent and never influenced by changes to the formatting features.

When users extend the contract editor component, can they control the width of the editor? For example, when Clause uses the contract editor component, do they set the width so that it fits within their UI?

**Comment by K-Kumar-01** [comment]
@irmerk @DianaLease 
Any updates here?

**Comment by irmerk** [comment]
I think this looks great! I think the padding on the icon is a little off, so @Michael-Grover up to you on that. There are some conflicts you'll want to rebase to resolve @K-Kumar-01.

Feels like a great testament to the foundations of the code that adding this support looks straightforward.

I think a follow up item to this will be that we may want to condense some of the icons into a dropdown (similar to the headings dropdown) to keep the width smaller. Thoughts @Michael-Grover?

**Comment by jeromesimeon** [comment]
> Feels like a great testament to the foundations of the code that adding this support looks straightforward.
> 

Couldn't agree more. It looks very clean.

I'm a little bit curious about the editing experience. E.g., what happens on delete inside a code block? If the code block is empty, does it get deleted? Also does it work with cut+paste?

**Comment by irmerk** [comment]
From @jeromesimeon's comments, some things we'll want to address:
- Cut or Copy and Paste results in an extra initial line in the code block
- Starting a code block and then pressing <kbd>ENTER</kbd> multiple times does not exit the code block

**Comment by Michael-Grover** [comment]
Following up on this comment because I want to make sure the width of the editor doesn't change every time we change the formatting toolbar:
> I'm interested in input on the width issues from someone who is more familiar with the contract editor than me, like @DianaLease or @irmerk. For context, I'd like to make sure the width of the contract editor is consistent and doesn't change by a few pixels whenever we make a change to the formatting toolbar. In Google Docs or Microsoft Word, the default document width is consistent and never influenced by changes to the formatting features.
> When users extend the contract editor component, can they control the width of the editor? For example, when Clause uses the contract editor component, do they set the width so that it fits within their UI?

> I think a follow up item to this will be that we may want to condense some of the icons into a dropdown (similar to the headings dropdown) to keep the width smaller. Thoughts @Michael-Grover?
I agree, this sounds like a good idea if we want more formatting options in the future.

@K-Kumar-01 In the screenshots you shared, it looks like something is going on with the end of the formatting toolbar
image

> I think this looks great! I think the padding on the icon is a little off, so @Michael-Grover up to you on that.
Yeah, now that you mention, the icon is a little bit lower than centered
image

**Comment by K-Kumar-01** [comment]
> I think this looks great! I think the padding on the icon is a little off, so @Michael-Grover up to you on that. There are some conflicts you'll want to rebase to resolve @K-Kumar-01.

@irmerk 
I will update my PR correspondingly to avoid any conflicts.

>I think a follow up item to this will be that we may want to condense some of the icons into a dropdown (similar to the headings dropdown) to keep the width smaller. Thoughts @Michael-Grover?

I think for this we can make another issue if required.


@Michael-Grover 
>@K-Kumar-01 In the screenshots you shared, it looks like something is going on with the end of the formatting toolbar

I will look to the following and give you an update regarding the same.

Also @irmerk
I have mentioned some contract editor images [here](https://github.com/accordproject/web-components/pull/289#issuecomment-803271308).
Can you also provide me updates here. I think this part got skipped.

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
> @K-Kumar-01 In the screenshots you shared, it looks like something is going on with the end of the formatting toolbar
> image

I think there might be some problem with the icon we are using. If I comment out the code or use any other icon for a code block, the page break icon displays correctly. However, if I use the icon which we are using currently, then the above error occurs.

**Comment by Michael-Grover** [comment]
@K-Kumar-01 so the new code block icon is affecting the page break icon?

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
In my opinion, yes the new code block icon is affecting the page-break icon.

**Comment by Michael-Grover** [comment]
@K-Kumar-01 could you investigate why this new icon may be affecting the others, so that when we add or change icons in the future, we can make sure it doesn't affect the appearance of other icons?

**Comment by K-Kumar-01** [comment]
> @K-Kumar-01 could you investigate why this new icon may be affecting the others, so that when we add or change icons in the future, we can make sure it doesn't affect the appearance of other icons?

@Michael-Grover 
Only this icon is being affected by the new code block icon, so is there a chance that the problem can be in the page break icon? 🤔

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I found a new icon that is causing no issues with the page break icon. The only thing is that the borders of the icon are a bit bold which I think you might be able to solve. 
Image with new code block icon.
Screenshot from 2021-04-08 12-59-26

Zip file
[icon.zip](https://github.com/accordproject/web-components/files/6276871/icon.zip)

**Comment by Michael-Grover** [comment]
@K-Kumar-01 thanks, this icon looks good but the color is not consistent with the other icons. I also think we should understand the underlying cause of why one icon is breaking another icon rather than replacing it, because when we want to add new icons in the future, we may face this same problem again. Is there anything in the code of the .svg file that looks wonky?

**Comment by K-Kumar-01** [comment]
> @K-Kumar-01 thanks, this icon looks good but the color is not consistent with the other icons. I also think we should understand the underlying cause of why one icon is breaking another icon rather than replacing it, because when we want to add new icons in the future, we may face this same problem again. Is there anything in the code of the .svg file that looks wonky?

@Michael-Grover 
I do not know much about the SVGs.
I was not able to find anything suspicious in the code block icon.
However, I was able to notice one thing. In all other icons, we have the path enclosed in `<g>` or`<svg>` tag. This is not the case with the `tbreak`(page-break) icon.
Also, since only the page-break icon has tampered, I think the issue might be lying in the page-break icon only.
What do you think?

**Comment by Michael-Grover** [comment]
@K-Kumar-01  the `<g>` or `<svg>` tag issue sounds promising, have you tried wrapping the page break icon in one of those tags to see if it works?

The color of the SVG can be changed on line 11 of the SVG file
`fill="#000000" stroke="none">`

**Comment by K-Kumar-01** [comment]
> @K-Kumar-01 the `<g>` or `<svg>` tag issue sounds promising, have you tried wrapping the page break icon in one of those tags to see if it works?
> 
> The color of the SVG can be changed on line 11 of the SVG file
> `fill="#000000" stroke="none">`

@Michael-Grover 
I didn't try as I was unsure about it. I will give it a go and let you know if I am able to make any progress.

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
The following image is of the old code block icon which was causing the issue. I have been able to fix it.
Screenshot from 2021-04-08 23-56-19

The thinking that `<g>` or `<svg>` tag was wrong it seems.
The actual issue was in the code_block icon itself.
```js
<style type="text/css" dangerouslySetInnerHTML={{__html: "\n    .st0 {\n      clip-path: url(#SVGID_2_);\n      fill: #949CA2;\n    }\n    .st1 {\n      fill: #949CA2;\n    }\n  " }} />
      <g>
        <defs>
          <path id="SVGID_1_" d="M1.9,0C0.8,0,0,0.8,0,1.9v13c0,1,0.8,1.9,1.9,1.9h13c1,0,1.9-0.8,1.9-1.9v-13c0-1-0.8-1.9-1.9-1.9H1.9z
          M14.5,1.3c0.5,0,0.9,0.4,0.9,0.9v12.3c0,0.5-0.4,0.9-0.9,0.9H2.2c-0.5,0-0.9-0.4-0.9-0.9V2.2c0-0.5,0.4-0.9,0.9-0.9H14.5z" />
        </defs>
        <clipPath id="SVGID_2_">
          <use xlinkHref="#SVGID_1_" style={{overflow: 'visible'}} />
        </clipPath>
        <rect className="st0" width="16.7" height="16.7" />
      </g>
```

Changing the above to this worked:
```js
<path fill="#949CA2" d="M1.9,0C0.8,0,0,0.8,0,1.9v13c0,1,0.8,1.9,1.9,1.9h13c1,0,1.9-0.8,1.9-1.9v-13c0-1-0.8-1.9-1.9-1.9H1.9z
        M14.5,1.3c0.5,0,0.9,0.4,0.9,0.9v12.3c0,0.5-0.4,0.9-0.9,0.9H2.2c-0.5,0-0.9-0.4-0.9-0.9V2.2c0-0.5,0.4-0.9,0.9-0.9H14.5z" />
```
Though I am able to resolve the issue, why the issue was caused due to this code is still unexplainable by me as I do not possess enough knowledge about SVGs, I think it might be due to `dangerouslySetInnerHTML` and due to `clipPath`. Not confirm though.

So shall we proceed with this icon?

**Comment by K-Kumar-01** [comment]
> Also @irmerk
> I have mentioned some contract editor images [here](https://github.com/accordproject/web-components/pull/289#issuecomment-803271308).
> Can you also provide me updates here. I think this part got skipped.

@irmerk 
Any updates on this one?

**Comment by irmerk** [comment]
I think we'll still want to address the issues I mentioned here https://github.com/accordproject/web-components/pull/289#issuecomment-812585457. 

As for width with the editor and toolbar, I think we can open an Issue after this PR that will consolidate sections of the toolbar (as I mentioned in this comment https://github.com/accordproject/web-components/pull/289#issuecomment-812579933). This way, any additions will go into these drop-downs and no affect any width.

**Review by dselman — APPROVED** [review]
Great!

**Comment by dselman** [comment]
@K-Kumar-01 please fix the merge conflict and I will merge the changes.

**Comment by K-Kumar-01** [comment]
> @K-Kumar-01 please fix the merge conflict and I will merge the changes.

A note here @dan. I was not able to see the changes which were mentioned in [this comment](https://github.com/accordproject/web-components/pull/289#issuecomment-812585457). So currently these features are still to be added.

**Comment by jeromesimeon** [comment]
> > @K-Kumar-01 please fix the merge conflict and I will merge the changes.
> 
> A note here @dan. I was not able to see the changes which were mentioned in [this comment](https://github.com/accordproject/web-components/pull/289#issuecomment-812585457). So currently these features are still to be added.

Hi @K-Kumar-01 Any update on this. I still see a merge conflict. I'll be happy to merge this PR once the conflict is resolved.

**Comment by K-Kumar-01** [comment]
> > > @K-Kumar-01 please fix the merge conflict and I will merge the changes.
> > 
> > 
> > A note here @dan. I was not able to see the changes which were mentioned in [this comment](https://github.com/accordproject/web-components/pull/289#issuecomment-812585457). So currently these features are still to be added.
> 
> Hi @K-Kumar-01 Any update on this. I still see a merge conflict. I'll be happy to merge this PR once the conflict is resolved.

@jeromesimeon 
Apologies for the delay.
Currently, I am preoccupied with some other stuff. Will look to this as soon as i get time.

**Comment by jeromesimeon** [comment]
> > > > @K-Kumar-01 please fix the merge conflict and I will merge the changes.
> > > 
> > > 
> > > A note here @dan. I was not able to see the changes which were mentioned in [this comment](https://github.com/accordproject/web-components/pull/289#issuecomment-812585457). So currently these features are still to be added.
> > 
> > 
> > Hi @K-Kumar-01 Any update on this. I still see a merge conflict. I'll be happy to merge this PR once the conflict is resolved.
> 
> @jeromesimeon
> Apologies for the delay.
> Currently, I am preoccupied with some other stuff. Will look to this as soon as i get time.

No worries! Thanks for the update. I'll leave this PR open.

**Comment by irmerk** [comment]
Closing for stale status. Reopen or use as reference when addressing #30

**Pull request closed without merging**
