### PR TITLE
chore(docs): updated the docs for Delete Edit and Test Icons

### LINKED ISSUE #271: Delete Icon Of Templates Not Working
# Bug Report 🐛
Click on Delete Icon is not working when the cursor hovers over clause templates.
Package: Contract Editor

## Expected Behavior

The template should get deleted.

## Current Behavior

There is no deletion of the template.

## Steps to Reproduce

1. Hover any template
2. Click on delete icon

### Desktop
 - OS: ZorinOs(Ubuntu based)
 - Browser: Chrome
 - Version: Chrome- 88.0.4324.182 (Official Build) (64-bit), Zorin OS 15.3

### PR DESCRIPTION
**Pull request by Cronus1007**
# Closes #271 
### Changes
- Updated the Docs for ui-contract-editor regarding the Clause Props Object 
- Linked README.md file of ui-contract-editor with that of contract-editor

### Related Issues
- Issue #271 
### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [x] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Review by irmerk — CHANGES_REQUESTED** [review]
Please rebase to remove merge commits.

Also, needs investigation by @accordproject/maintainers-ui.

**Review by irmerk — CHANGES_REQUESTED** [review]
Can you rebase? I had updated some of this in #324

I'm not sure I understand the **Overview** section: 

> The Contract Editor tool gives you the ability to examine and edit class contracts in a context that is isolated from the full class text. In other words, when you use the Contract Editor tool, you see and edit the contracts without having to work around other elements of the software text such as implementation.For routines, you can edit pre- and postconditions, and for classes, you can edit class invariants. The tool provides views of inherited contracts as well as immediate ones.

What are these?
- Class contract
- Class text
- Class invariants
- Implementation (an element of the software text?)
- Inherited contract
- Immediate contract

**Comment by Cronus1007** [comment]
@irmerk I have resolved merge conflicts plus changed a little bit of overview as well.

**Comment by irmerk** [comment]
Closing because I think the `Overview of Contract Editor Tool` section is explained in other locations like the `techdocs` repository, the `Overview of Clause Props Object` section is explained just after this addition, and the last section is handled in another PR..

**Comment by Cronus1007** [comment]
@irmerk So any updates about the issue #271.This one can also be closed since you added the required code block which got erased to resolve the merge conflicts.

**Pull request closed without merging**
