### PR TITLE
feat(contract-editor) : Slate rendering of read-only variables

### LINKED ISSUE #194: Read-only variables
# Feature Request 🛍️

In some cases it is useful to be able to tag a variable as read-only, such that it is present in the document, but can not be edited.

## Use Case
This will be used for signature blocks.

## Possible Solution
Look for the `ContractEditor("readOnly") decorator on the model element.

### PR DESCRIPTION
**Pull request by dselman**
Signed-off-by: Dan Selman <danscode@selman.org>

# Closes #194 

Adds support for the `@ContractEditor` decorator, which can be added any Concerto types that are used as variables. Use this decorator to apply selective styles to variables, or to mark them as read-only. Example:

```
asset TitleNameDateSignatureBlock extends SignatureClause {
  @ContractEditor("readOnly", true, 
    "fontFamily", "Lucida Console, Courier, monospace",
    "backgroundColor", "#FAE094", "border", '#CCA855' )
  o String title
```

The variable `title` will be rendered using a custom background and border color, using a monospace font and is read-only.

### Changes
- Checks whether the readOnly decorator is present on a variable to determine whether it can be edited
- Updates the styling rules for variables based on the decorator

### Flags
- Can still click into readOnly variables, though they cannot be edited

### Screenshots or Video

image (3)

### Author Checklist
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [x] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [x] Manual accessibility test performed
    - [x] Keyboard-only access, including forms
    - [x] Contrast at least WCAG Level A
    - [x] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Review by DianaLease — APPROVED** [review]
Awesome!!

**Comment by dselman** [comment]
I updated the PR to support specifying read-only and opacity independently and switched to using the more robust `Decorators` utility class which was added to `markdowna-cicero` package.

**Review by DianaLease — APPROVED** [review]
This looks great to me! I would just get @Michael-Grover 's feedback on this styling for the read only variables if you haven't already.

**Comment by dselman** [comment]
> This looks great to me! I would just get @Michael-Grover 's feedback on this styling for the read only variables if you haven't already.

@Michael-Grover note that none of the styles are hard-coded - the background colour, border colour font-face and opacity are specified by the user using decorators on the Concerto mode.

**Comment by irmerk** [comment]
These decorators are coming from [this issue in `markdown-transform`](https://github.com/accordproject/markdown-transform/issues/249), correct?

**Comment by jeromesimeon** [comment]
> These decorators are coming from [this issue in `markdown-transform`](https://github.com/accordproject/markdown-transform/issues/249), correct?

yep

**Review by DianaLease — APPROVED** [review]
LGTM!

**Pull request merged**
