### PR TITLE
feat(ui-contract-editor):drag&drop disabled for embeded clauses

### LINKED ISSUE #178: Don't let users drag and drop embedded clauses
# Feature Request 🛍️
Make it clear that users can not drag and drop embedded clauses. Embedded clauses currently have the same drag and drop UI as normal smart clause templates, implying that they can be dragged and dropped.

## Possible Solution
Remove drag and drop UI from embedded Clauses and give some padding so the borders aren't intersecting with the parent clause

This examples is in the copyright license Clause
image

### PR DESCRIPTION
**Pull request by sanketshevkar**
Signed-off-by: User <shevkar.sanket@gmail.com>

# Closes #178 

### Changes

- String match with clause header, if header length is 0 then disable the clause ui-icons.
- padding added to clause wrapper

### Related Issues
- Issue #178 
### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by irmerk** [comment]
@sanketshevkar it looks like Netlify timed out, can you force push your same code to kickstart the Netlify process again?

**Comment by sanketshevkar** [comment]
> @sanketshevkar it looks like Netlify timed out, can you force push your same code to kickstart the Netlify process again?

Ok, Sure.

**Comment by irmerk** [comment]
Hmm I'm not sure how checking the header length helps here? Could you elaborate?

**Comment by sanketshevkar** [comment]
> Hmm I'm not sure how checking the header length helps here? Could you elaborate?

The header for an embedded clause is empty, so if the length of the header of a clause is 0, then don't allow the drag and drop icons get displayed.

**Review by dselman — APPROVED** [review]
We will have to think about a more reliable mechanism to identify embedded clauses, but this works for now.

**Comment by irmerk** [comment]
@dselman I believe your changes broke the PR.

**Comment by dselman** [comment]
> @dselman I believe your changes broke the PR.

Work on it.

**Pull request merged**
