### PR TITLE
fix(ui-markdown-editor):multi-para to list proper indent - I158

### LINKED ISSUE #158: Changing a group of paragraphs to a numbered list only indents the paragraphs
# Bug Report 🐛
If the user highlights a group of paragraphs and clicks the numbered or bulleted list icons, the paragraphs are indented, but not given a bullet or a number.

image

## Expected Behavior
Highlighting a group of paragraphs and clicking the numbered or bulleted list icons should turn the highlighted text into a numbered or bulleted list

video:
https://www.loom.com/share/64f31fb19dd346ab971859ff2a28a0dc

### PR DESCRIPTION
**Pull request by K-Kumar-01**
Signed-off-by: k-kumar-01 <kushalkumargupta4@gmail.com>

# Closes #158 
Choosing multiple paragraphs and then converting them to list will now show points-bullet or numbers along with the indentation

### Changes

- Need to change the anchor and focus when selecting from bottom

### Screenshots or Video

Selecting from bottom
Screenshot from 2021-02-20 23-49-03
Result
Screenshot from 2021-02-20 23-49-10

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by Michael-Grover** [comment]
@K-Kumar-01 , it looks like there are some unsuccessful checks. If you need help, I recommend asking @irmerk or @dselman

**Comment by K-Kumar-01** [comment]
> @K-Kumar-01 , it looks like there are some unsuccessful checks. If you need help, I recommend asking @irmerk or @dselman
@Michael-Grover 
I am unable to understand the failure of the checks.
@irmerk @dselman 
Could you please tell me what is the error?

**Comment by irmerk** [comment]
The error logs look strange to me... @K-Kumar-01 I'd suggest force pushing the same code up to force Netlify to rebuild and we can see what the issue is.

**Comment by K-Kumar-01** [comment]
> The error logs look strange to me... @K-Kumar-01 I'd suggest force pushing the same code up to force Netlify to rebuild and we can see what the issue is.

@irmerk 
I have added a commit(comment added) as I was not confident about force push.
@Michael-Grover 
The PR build is successful now. Let me know if there are any changes required.

**Review by dselman — APPROVED** [review]
LGTM!

**Pull request merged**
