### PR TITLE
fix(ui-contract-editor) prevent sig variable edits on readOnly - I212

### LINKED ISSUE #212: Read-only variables are editable if you insert text at position 0
# Bug Report 🐛
Variables that are marked as read-only using a decorator are editable if you place your cursor position just before the first character of the variable and type.

## Expected Behavior
Should not be able to edit read-only variables.

## Current Behavior
Can insert characters before the first character of the variable.

## Steps to Reproduce
1. Add a signature block
2. Position cursor before the first character of the variable
3. Type

image

### Desktop
 - OS: Mac OS
 - Browser: Safari
 - Version: Latest

### PR DESCRIPTION
**Pull request by sanketshevkar**
…#212)

Signed-off-by: User <shevkar.sanket@gmail.com>

# Closes #212 

### Changes

- Check whether the variable is editable or not.
- A condition is added which checks it and prevents editing of the variable if it is read-only.

### Related Issues
- Issue #212 

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by irmerk** [comment]
Functionally looks to work, I need to look into the code a bit more soon to make sure that this is doing what we want it to do.

**Comment by Michael-Grover** [comment]
I don't see a difference in functionality between this and the current contract editor set to read only. Both appear to not even allow the user to highlight read only text. It looks like there is a bigger issue here, because a user should be highlight read only text, for example if they want to copy and paste it.

**Comment by Michael-Grover** [comment]
I am not able to replicate the original bug from [212](https://github.com/accordproject/web-components/issues/212). It appears that when a contract is read only, the user can't put the text cursor in a clause template or signature block. Is anyone else able to replicate the original bug? I think there is a bigger issue if users can't highlight read only text. A user should be able to copy and paste read only text.

**Review by Michael-Grover — APPROVED** [review]
Ignore my previous comments that I deleted, I misunderstood what the bug was for a while. It looks like this works. Please wait for @irmerk's approval of the code before merging. Thanks!

**Review by dselman — APPROVED** [review]
Great job -- this one is definitely tricky!

**Comment by sanketshevkar** [comment]
> Great job -- this one is definitely tricky!

Thank you @dselman :)

**Pull request merged**
