### PR TITLE
feat(ui-contract-editor):disable cursor caret for read-only text

### LINKED ISSUE #248: Not allowing cursor caret in non-editable clause text
# Feature Request 🛍️

## Use Case

When cursor caret is blinking inside the non-editable clause text, it feels as if that text is editable. Since the text is read-only, cursor caret should not be allowed to place inside the clause text.

## Possible Solution

Set `caret-color: transparent;` for read-only text.

### PR DESCRIPTION
**Pull request by sanketshevkar**
Signed-off-by: User <shevkar.sanket@gmail.com>

# Closes #248 

### Changes

- `caret-color` set for variales and clause-body

### Flags

- Cursor caret for read-only variables is still active.

### Related Issues
- Issue #248 
- Pull Request #<NUMBER>

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Review by dselman — CHANGES_REQUESTED** [review]
I don't think this really works from a usability point of view because when you press the down/up arrow to move through the text, as soon as your cursor position moves within a clause it disappears. Eventually it will reappear when it exits the clause, but during the intervening period you don't get any feedback on cursor position. The cursor will also reappear if you happen to move through a variable.

I don't know what the "right" answer is, but I feel that the current cursor handling is preferable.

**Comment by irmerk** [comment]
I agree on Dan's points. Pinging @Michael-Grover on this one.

**Comment by Michael-Grover** [comment]
I also agree with Dan. I'm not aware of any instances of read only text that make the cursor carat invisible.

**Comment by Michael-Grover** [comment]
Sorry, closed by accident when I was seeing if a cursor carat would appear when I highlighted the text on github's buttons. I agree with @dselman. I don't see a convincing justification for changing the current functionality.

**Comment by sanketshevkar** [comment]
> I don't think this really works from a usability point of view because when you press the down/up arrow to move through the text, as soon as your cursor position moves within a clause it disappears. Eventually it will reappear when it exits the clause, but during the intervening period you don't get any feedback on cursor position. The cursor will also reappear if you happen to move through a variable.
> 
> I don't know what the "right" answer is, but I feel that the current cursor handling is preferable.

Cool, no problem :). My motive was to somehow distinguish between read-only and editable text. When I, for the first time saw the cursor blinking inside the clause, I thought the clause text was editable, it took me a while to understand that it was read-only text. So I thought this solution might help.

**Pull request closed without merging**
