### PR TITLE
fix(ui-markdown-editor): quotes button working

### LINKED ISSUE #255: Quotes icon not working.
If the user highlights a paragraph or a group of paragraphs and clicks the quotes icons, the paragraphs are just indented, but not wrapped in quotes.
# Bug Report 🐛

## Expected Behavior

On clicking the quotes button, the text or selected paragraph should be wrapped inside quotes.

## Current Behavior

Below is link to the recorded video of the current behavior.
https://www.loom.com/share/8bcb3f2d4f8d4bc091176be1bf2f7263

### PR DESCRIPTION
**Pull request by gatij10**
Signed-off-by: Gatij Taranekar <gatij.taranekar@gmail.com>

# Closes #255 

### Changes

- <ONE> Wrapped the selected text around a q tag.

### Screenshots or Video

https://www.loom.com/share/1757da27eb7c42349c785e3b53506a9e

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

**Comment by dselman** [comment]
Your fix works, but I don't understand why we need *both* `<blockquote>` and `<q>` tags.

My understand is that `<blockquote>` should be used for quoted paragraphs, while `<q>` is for shorter inline quotes.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/q

It feels like this could be a css issue with the `<blockquote>` tag. 
https://css-tricks.com/examples/Blockquotes/

Could you please investigate whether we can apply css to the `<blockquote>` tag to fix this, rather than wrapping everything in `<q>`?

**Review by dselman — CHANGES_REQUESTED** [review]
Please investigate whether css targeted at `<blockquote>` can fix this.

**Comment by gatij10** [comment]
@dselman I have added Css to the blockquotes and deleted the q tag.
https://www.loom.com/share/ba4f2ae08be648d6bcc01ac9a53a4f7b

**Review by irmerk — CHANGES_REQUESTED** [review]
Can you revert all the linting changes made? I can't really tell where actual code is being changed.

**Pull request closed without merging**
