### PR TITLE
style(src): add border to Editable component - I51

### LINKED ISSUE #51: UI Realignment
In the Slate migration, we have strayed a bit from the original editor styling. We need to ensure this is back on to specification, both in `cicero-ui` and in a parent component.

What should the “_out of the box_” style look like if someone wants to just import this component and be done with it?

We need to decide what style / design we want in `markdown-editor` (`RichTextEditor`) _and_ `cicero-ui` (`ContractEditor`)

**NOTE**: Code addressing this issue should be overridable via CSS by a parent component.

### PR DESCRIPTION
**Pull request by justinclanglinais**
# Closes #51 
Re-align UI to Accord Project spec

### Changes
- adjust box shadow to spec (5px bottom)
- add border to Editable component (1px gray, 4px radius)

### Author Checklist
- [X] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [X] Merging to `master` from `fork:branchname`

### CODE REVIEW

**Review by Michael-Grover — APPROVED** [review]
it took me a while to figure out the box shadow is white. I was looking for a shadow and couldn't find it 🤦 . lgtm, thanks!

**Comment by irmerk** [comment]
@Michael-Grover do we feel like this solves #51 entirely? This will also make a border around the editor, but I believe we will be able to override it or remove it with the `id: ap-rich-text-editor` attribute.

**Review by irmerk — APPROVED** [review]

**Comment by Michael-Grover** [comment]
#51 has a lot of discussion in the issue, and I'm not sure what the original motivation behind the issue was, but I think this addresses the last comment I made in the issue @irmerk

**Review by DianaLease — APPROVED** [review]
👍

**Comment by irmerk** [comment]
@justinclanglinais can you force push again with nothing changed to jump start these Netlify checks so we can pass and get this merged?

**Pull request merged**
